// Generates committed map/flag assets into packages/ui/src/generated/.
// Run: pnpm --filter @mathfamily/design-assets generate   (needs network for flags)
import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, "../../packages/ui/src/generated");

// world-atlas numeric ids → iso2, for the 40 RoamMath destinations
const N3_TO_A2 = {
  "724": "es", "250": "fr", "380": "it", "620": "pt", "300": "gr", "276": "de",
  "372": "ie", "528": "nl", "056": "be", "040": "at", "756": "ch", "616": "pl",
  "191": "hr", "196": "cy", "470": "mt", "792": "tr", "840": "us", "124": "ca",
  "484": "mx", "036": "au", "554": "nz", "784": "ae", "764": "th", "392": "jp",
  "156": "cn", "356": "in", "710": "za", "818": "eg", "504": "ma", "788": "tn",
  "578": "no", "352": "is", "752": "se", "208": "dk", "203": "cz", "348": "hu",
  "642": "ro", "100": "bg", "008": "al", "499": "me"
};

const D2R = Math.PI / 180;
// Spherical mercator. y grows downward (screen space). Lat clamped for sanity.
function merc([lng, lat]) {
  const phi = Math.max(-60, Math.min(84, lat)) * D2R;
  return [lng * D2R, -Math.log(Math.tan(Math.PI / 4 + phi / 2))];
}

function* points(geom) {
  const polys = geom.type === "Polygon" ? [geom.coordinates] : geom.coordinates;
  for (const poly of polys) for (const ring of poly) for (const pt of ring) yield pt;
}

function makeFit(geoms, width) {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const g of geoms) for (const pt of points(g)) {
    const [x, y] = merc(pt);
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
  }
  const s = width / (maxX - minX);
  const height = Math.ceil((maxY - minY) * s);
  return {
    project: (pt) => { const [x, y] = merc(pt); return [(x - minX) * s, (y - minY) * s]; },
    constants: { s, minX, minY },
    viewBox: `0 0 ${width} ${height}`
  };
}

function geomToPath(geom, project) {
  const polys = geom.type === "Polygon" ? [geom.coordinates] : geom.coordinates;
  let d = "";
  for (const poly of polys) for (const ring of poly) {
    ring.forEach((pt, i) => {
      const [x, y] = project(pt);
      d += `${i === 0 ? "M" : "L"}${x.toFixed(1)} ${y.toFixed(1)}`;
    });
    d += "Z";
  }
  return d;
}

function bboxCenter(geom, project) {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const pt of points(geom)) {
    const [x, y] = project(pt);
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
  }
  return [((minX + maxX) / 2).toFixed(1), ((minY + maxY) / 2).toFixed(1)];
}

const HEADER = "// GENERATED by tools/design-assets/generate.mjs — DO NOT EDIT.\n// Regenerate: pnpm --filter @mathfamily/design-assets generate\n";

await mkdir(OUT, { recursive: true });

// ── UK (50m for a decent coastline) ──────────────────────────────
{
  const topo = require("world-atlas/countries-50m.json");
  const gb = feature(topo, topo.objects.countries).features.find((f) => f.id === "826" || f.id === 826);
  if (!gb) throw new Error("GB not found in countries-50m");
  const fit = makeFit([gb.geometry], 200);
  const d = geomToPath(gb.geometry, fit.project);
  const { s, minX, minY } = fit.constants;
  await writeFile(path.join(OUT, "uk-path.ts"), `${HEADER}
export const UK_VIEWBOX = ${JSON.stringify(fit.viewBox)};
export const UK_PATH = ${JSON.stringify(d)};
const S = ${s}, MINX = ${minX}, MINY = ${minY};
const D2R = Math.PI / 180;
/** Project lat/lng to UK_VIEWBOX coordinates (same mercator fit as UK_PATH). */
export function ukProject(lat: number, lng: number): [number, number] {
  const x = lng * D2R;
  const y = -Math.log(Math.tan(Math.PI / 4 + (lat * D2R) / 2));
  return [(x - MINX) * S, (y - MINY) * S];
}
`);
}

// ── World (110m): outline + per-destination paths & centroids ────
// Note: some small countries (e.g. Malta/470) are absent from 110m; we fall
// back to 50m features for those, projected into the same 110m fit.
{
  const topo = require("world-atlas/countries-110m.json");
  const topo50 = require("world-atlas/countries-50m.json");
  const feats50all = feature(topo50, topo50.objects.countries).features;
  const feats = feature(topo, topo.objects.countries).features.filter((f) => f.id !== "010" && f.id !== 10); // drop Antarctica
  const fit = makeFit(feats.map((f) => f.geometry), 1000);
  const outline = feats.map((f) => geomToPath(f.geometry, fit.project)).join("");
  const paths = {}, centroids = {};
  for (const f of feats) {
    const a2 = N3_TO_A2[String(f.id).padStart(3, "0")];
    if (!a2) continue;
    paths[a2] = geomToPath(f.geometry, fit.project);
    centroids[a2] = bboxCenter(f.geometry, fit.project).map(Number);
  }
  // Fall back to 50m for small countries missing from 110m atlas
  const missing = Object.entries(N3_TO_A2).filter(([, a2]) => !paths[a2]);
  for (const [n3, a2] of missing) {
    const f50 = feats50all.find((f) => String(f.id).padStart(3, "0") === n3);
    if (!f50) throw new Error(`country ${n3} (${a2}) missing from both 110m and 50m atlas`);
    paths[a2] = geomToPath(f50.geometry, fit.project);
    centroids[a2] = bboxCenter(f50.geometry, fit.project).map(Number);
    console.log(`  fallback to 50m for ${a2} (${n3})`);
  }
  await writeFile(path.join(OUT, "world-paths.ts"), `${HEADER}
export const WORLD_VIEWBOX = ${JSON.stringify(fit.viewBox)};
export const WORLD_OUTLINE = ${JSON.stringify(outline)};
export const COUNTRY_PATHS: Record<string, string> = ${JSON.stringify(paths)};
export const COUNTRY_CENTROIDS: Record<string, [number, number]> = ${JSON.stringify(centroids)};
`);
}

// ── Flags (circle-flags, MIT) for the 40 destinations + gb ───────
{
  const codes = [...new Set([...Object.values(N3_TO_A2), "gb"])].sort();
  const flags = {};
  for (const a2 of codes) {
    const res = await fetch(`https://raw.githubusercontent.com/HatScripts/circle-flags/gh-pages/flags/${a2}.svg`);
    if (!res.ok) throw new Error(`flag ${a2}: HTTP ${res.status}`);
    const svg = await res.text();
    flags[a2] = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
  }
  await writeFile(path.join(OUT, "flags.ts"), `${HEADER}
// Flag artwork: HatScripts/circle-flags (MIT). Inner markup of 512x512 viewBox SVGs.
export const FLAGS: Record<string, string> = ${JSON.stringify(flags)};
`);
}

console.log("generated:", OUT);
